#!/bin/bash

# Use manifest-tool to create the manifest, given the experimental
# "docker manifest" command isn't available yet on Docker Hub
echo get manifest tool
curl -Lo manifest-tool https://github.com/estesp/manifest-tool/releases/download/v1.0.2/manifest-tool-linux-amd64
chmod +x manifest-tool
echo start of manifest tool
./manifest-tool push from-args --platforms linux/arm/v7 --template wagoautomation/pfc-modbus-server:${DOCKER_TAG} --target wagoautomation/pfc-modbus-server:${DOCKER_TAG}
echo end of manifest tool